version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
    restart: always
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 8080
      AUTHENTICATION_SERVICE_ADDRESS: authentication-service:5001
      AUTHENTICATION_SERVICE_METHOD: Server.Authenticate
      LOGGER_SERVICE_ADDRESS: logger-service:5001
      LOGGER_SERVICE_METHOD: Server.LogInfo
      MAIL_SERVICE_ADDRESS: mail-service:5001
      MAIL_SERVICE_METHOD: Server.SendMail

  logger-service:
    build:
      context: ./../logger-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5001
      MONGO_URL: 'mongodb://mongo:27017'

  authentication-service:
    build:
      context: ./../authentication-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5001
      DSN: 'host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5'
      LOGGER_SERVICE_ADDRESS: logger-service:5001

  mail-service:
    build:
      context: ./../mail-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 5001
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      MAIL_ENCRYPTION: 'none'
      FROM_NAME: 'John Smith'
      FROM_ADDRESS: 'johnsmith@example.com'

  postgres:
    image: 'postgres:14.0'
    platform: linux/amd64
    ports:
      - '5432:5432'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  mongo:
    image: 'mongo:4.2.16-bionic'
    platform: linux/amd64
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'jcalonso/mailhog:latest'
    platform: linux/amd64
    ports:
      - '1025:1025'
      - '8025:8025'
