name: Go Micro - build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test broker-service
        run: cd broker-service && go test -v ./...

      - name: Test authentication-service
        run: cd authentication-service && go test -v ./...

      - name: Test logger-service
        run: cd logger-service && go test -v ./...

      - name: Test mail-service
        run: cd mail-service && go test -v ./...
